from dataclasses import dataclass, field
from typing import Optional, Dict, Any
from datetime import datetime

@dataclass
class AgentSignal:
    """
    Standard contract for Agent output signals.
    Enforces strict typing for inter-agent communication.
    """
    source: str                 # Name of the agent (e.g., "TechnicalAgent")
    signal: str                 # "BUY", "SELL", "NONE"
    confidence: float           # 0.0 to 1.0
    reason: str                 # Human-readable explanation
    symbol: str                 # The asset symbol (e.g., "EURUSD")
    timestamp: datetime = field(default_factory=datetime.now)
    ttl_seconds: int = 60       # Time-to-live for this signal
    metadata: Dict[str, Any] = field(default_factory=dict)

    def is_valid(self) -> bool:
        """Checks if the signal is still valid based on TTL"""
        age = (datetime.now() - self.timestamp).total_seconds()
        return age <= self.ttl_seconds

@dataclass
class TradeRequest:
    """
    Standard contract for Execution requests.
    Generated by the Risk/Strategy layer, consumed by Execution layer.
    """
    symbol: str
    action: str                 # "BUY", "SELL"
    volume: float
    sl_price: Optional[float] = None
    tp_price: Optional[float] = None
    sl_pips: Optional[int] = None
    tp_pips: Optional[int] = None
    magic_number: int = 0
    comment: str = ""
    
@dataclass
class ExecutionResult:
    """
    Standard contract for Execution results.
    Returned by the Execution layer.
    """
    success: bool
    ticket: int
    volume: float
    price: float
    error: Optional[str] = None
    timestamp: datetime = field(default_factory=datetime.now)
